name: Build Docker image

on:
  push:

jobs:
  build:
    uses: ./.github/workflows/buildx.yml
    needs: CI
    with:
      image: datatrash/beatlocker-server
    secrets:
      container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
      container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
